import type { Site } from "@/types";

export const siteConfig: Site = {
  name: "thefarid.xyz",
  title: "Md Farid | Building, Learning & Growing",
  description:
    "Hi, I'm Md Farid — a full-stack developer passionate about Web2 and Web3, AI, and building practical solutions to real-world problems.",
  keywords: [
  "md farid",
  "mdfarid",
  "portfolio",
  "mdfarid portfolio",
  "mdfarid 100x dev",
    "full stack developer",
    "web developer",
    "react developer",
    "next.js developer",
    "frontend developer",
    "backend developer",
    "mern developer",
    "portfolio website",
    "portfolio 2024",
    "portfolio 2025",
    "cognitive games",
    "ai projects",
    "game based aptitude testing",
    "placement preparation",
  "mdfarid portfolio 2024",
  "mdfarid portfolio 2025",
  "mdfarid website",
  "mdfarid portfolio website",
  "md farid portfolio website",
  ],
  siteUrl: "https://www.thefarid.xyz",
  ogImage: "https://www.thefarid.xyz/meta_thumb.png",
  creator: {
    name: "Md Farid",
    url: "https://www.thefarid.xyz",
  },
  links: {
    x: "https://x.com/MdFarid7886",
    github: "https://github.com/mdfarid01",
    linkedin: "https://www.linkedin.com/in/md-farid-1aa563291/",
  },
};
